export const SLIDES = [
  {
    id: '01',
    shortTitle: 'N°19',
    stepLabel: 'N°19 EAU DE PARFUM',
    title: 'N°19 CHANEL',
    subtitle: 'THE SIGNATURE IMPRESSION',
    oneLiner: 'An audacious harmony of crisp green notes and rare white florals.',
    tagline: 'Green Floral Masterpiece',
    description: 'An audacious, uncompromising harmony of crisp green botanical notes and rare white flowers. Created as Coco Chanel\'s final personal fragrance signature.',
    /* Previous: accent: '#8A9A86' */
    bg: '#FFFFFF',
    text: '#111111',
    secondaryText: '#555555',
    accent: '#059669',
    noteCategory: 'ALDEHYDIC GREEN',
    keyNotes: ['Galbanum', 'Iris Pallida', 'Haitian Vetiver'],
    pose: {
      rotation: [0, 0, 0],
    },
  },
  {
    id: '02',
    shortTitle: 'BERGAMOT',
    stepLabel: 'TOP NOTES',
    title: 'BERGAMOT & NEROLI',
    subtitle: 'VIBRANT BOTANICAL OVERTURE',
    oneLiner: 'An exhilarating burst of Italian Bergamot, Neroli, and resinous Galbanum.',
    tagline: 'Luminous Opening Accord',
    description: 'An exhilarating burst of Italian Bergamot, sun-drenched Neroli, and resinous Galbanum that ignites the senses with sharp, refined vitality.',
    /* Previous: accent: '#C08A3E' */
    bg: '#FFFFFF',
    text: '#111111',
    secondaryText: '#555555',
    accent: '#EA580C',
    noteCategory: 'CITRUS & GALBANUM',
    keyNotes: ['Calabrian Bergamot', 'Grasse Neroli', 'Iranian Galbanum'],
    pose: {
      rotation: [0.08, Math.PI / 3, 0],
    },
  },
  {
    id: '03',
    shortTitle: 'IRIS',
    stepLabel: 'HEART NOTES',
    title: 'IRIS PALLIDA & ROSE',
    subtitle: 'FLORAL NOBILITY & ELEGANCE',
    oneLiner: 'Precious Florentine Iris Pallida interwoven with May Rose absolute and Jasmine.',
    tagline: 'Powdery Velvet Core',
    description: 'The precious Iris Pallida from Florence unveils its velvety iris butter tone, seamlessly interwoven with May Rose absolute and silk Jasmine.',
    /* Previous: accent: '#B5838D' */
    bg: '#FFFFFF',
    text: '#111111',
    secondaryText: '#555555',
    accent: '#D946EF',
    noteCategory: 'PRECIOUS FLORALS',
    keyNotes: ['Florentine Iris', 'May Rose Absolute', 'Grasse Jasmine'],
    pose: {
      rotation: [-0.05, Math.PI * 0.7, 0.03],
    },
  },
  {
    id: '04',
    shortTitle: 'VETIVER',
    stepLabel: 'BASE NOTES',
    title: 'VETIVER & CEDAR',
    subtitle: 'EARTHY & WOODEN ANCHOR',
    oneLiner: 'Deep Haitian Vetiver and Sandalwood grounding a trail of smoked woods.',
    tagline: 'Smoky Amber Drydown',
    description: 'Deep Haitian Vetiver and creamed Sandalwood ground the composition with an enduring, sophisticated trail of smoked woods and quiet warmth.',
    /* Previous: accent: '#5E7465' */
    bg: '#FFFFFF',
    text: '#111111',
    secondaryText: '#555555',
    accent: '#0284C7',
    noteCategory: 'WOODS & AMBER',
    keyNotes: ['Haitian Vetiver', 'Virginia Cedarwood', 'White Musk'],
    pose: {
      rotation: [0.1, Math.PI, -0.05],
    },
  },
  {
    id: '05',
    shortTitle: 'MASTER',
    stepLabel: 'THE ELIXIR',
    title: 'MASTER ALCHEMY',
    subtitle: 'CRAFTED IN GRASSE',
    oneLiner: 'Crafted in limited harvests in Grasse, capturing green freshness & warmth.',
    tagline: 'Artisanal Enfleurage',
    description: 'Distilled in limited harvests in Grasse, France. Every drop captures the delicate balance between green freshness and opulent floral warmth.',
    /* Previous: accent: '#4A6B82' */
    bg: '#FFFFFF',
    text: '#111111',
    secondaryText: '#555555',
    accent: '#7C3AED',
    noteCategory: 'HAUTE PARFUMERIE',
    keyNotes: ['Small Batch Harvest', 'Enfleurage Extraction', 'Pure Concentrate'],
    pose: {
      rotation: [0.12, Math.PI * 1.4, 0.06],
    },
  },
  {
    id: '06',
    shortTitle: 'AN',
    stepLabel: 'THE COLLECTION',
    title: 'AN ICONIC LEGACY',
    subtitle: 'TIMELESS MONOLITH',
    oneLiner: 'Encased in a minimalist glass monolith, an enduring symbol of modern luxury.',
    tagline: 'Architectural Heritage',
    description: 'Encased within the minimalist faceted glass monolith. An enduring symbol of independence, courage, and modern luxury design.',
    /* Previous: accent: '#8A7B6B' */
    bg: '#FFFFFF',
    text: '#111111',
    secondaryText: '#555555',
    accent: '#D97706',
    noteCategory: 'COLLECTOR EDITION',
    keyNotes: ['Faceted Glass Flacon', 'Hand-Sealed Baudruchage', 'Chanel Seal'],
    pose: {
      rotation: [0, Math.PI * 2, 0],
    },
  },
];
