export const SLIDES = [
  {
    id: '01',
    shortTitle: 'N°19',
    stepLabel: '01 // N°19 EAU DE PARFUM',
    title: 'N°19 CHANEL',
    subtitle: 'THE SIGNATURE IMPRESSION',
    tagline: 'Green Floral Masterpiece',
    description: 'An audacious, uncompromising harmony of crisp green botanical notes and rare white flowers. Created as Coco Chanel\'s final personal fragrance signature.',
    bg: '#FFFFFF',
    text: '#1A1A1A',
    secondaryText: '#737373',
    accent: '#8A9A86',
    noteCategory: 'ALDEHYDIC GREEN',
    keyNotes: ['Galbanum', 'Iris Pallida', 'Haitian Vetiver'],
    pose: {
      rotation: [0, 0, 0],
    },
  },
  {
    id: '02',
    shortTitle: 'BERGAMOT',
    stepLabel: '02 // TOP NOTES',
    title: 'BERGAMOT & NEROLI',
    subtitle: 'VIBRANT BOTANICAL OVERTURE',
    tagline: 'Luminous Opening Accord',
    description: 'An exhilarating burst of Italian Bergamot, sun-drenched Neroli, and resinous Galbanum that ignites the senses with sharp, refined vitality.',
    bg: '#FAFAFA',
    text: '#1A1A1A',
    secondaryText: '#737373',
    accent: '#C08A3E',
    noteCategory: 'CITRUS & GALBANUM',
    keyNotes: ['Calabrian Bergamot', 'Grasse Neroli', 'Iranian Galbanum'],
    pose: {
      rotation: [0.08, Math.PI / 3, 0],
    },
  },
  {
    id: '03',
    shortTitle: 'IRIS',
    stepLabel: '03 // HEART NOTES',
    title: 'IRIS PALLIDA & ROSE',
    subtitle: 'FLORAL NOBILITY & ELEGANCE',
    tagline: 'Powdery Velvet Core',
    description: 'The precious Iris Pallida from Florence unveils its velvety iris butter tone, seamlessly interwoven with May Rose absolute and silk Jasmine.',
    bg: '#FBFBFB',
    text: '#1A1A1A',
    secondaryText: '#737373',
    accent: '#B5838D',
    noteCategory: 'PRECIOUS FLORALS',
    keyNotes: ['Florentine Iris', 'May Rose Absolute', 'Grasse Jasmine'],
    pose: {
      rotation: [-0.05, Math.PI * 0.7, 0.03],
    },
  },
  {
    id: '04',
    shortTitle: 'VETIVER',
    stepLabel: '04 // BASE NOTES',
    title: 'VETIVER & CEDAR',
    subtitle: 'EARTHY & WOODEN ANCHOR',
    tagline: 'Smoky Amber Drydown',
    description: 'Deep Haitian Vetiver and creamed Sandalwood ground the composition with an enduring, sophisticated trail of smoked woods and quiet warmth.',
    bg: '#FAFAFA',
    text: '#1A1A1A',
    secondaryText: '#737373',
    accent: '#5E7465',
    noteCategory: 'WOODS & AMBER',
    keyNotes: ['Haitian Vetiver', 'Virginia Cedarwood', 'White Musk'],
    pose: {
      rotation: [0.1, Math.PI, -0.05],
    },
  },
  {
    id: '05',
    shortTitle: 'MASTER',
    stepLabel: '05 // THE ELIXIR',
    title: 'MASTER ALCHEMY',
    subtitle: 'CRAFTED IN GRASSE',
    tagline: 'Artisanal Enfleurage',
    description: 'Distilled in limited harvests in Grasse, France. Every drop captures the delicate balance between green freshness and opulent floral warmth.',
    bg: '#FFFFFF',
    text: '#1A1A1A',
    secondaryText: '#737373',
    accent: '#4A6B82',
    noteCategory: 'HAUTE PARFUMERIE',
    keyNotes: ['Small Batch Harvest', 'Enfleurage Extraction', 'Pure Concentrate'],
    pose: {
      rotation: [0.12, Math.PI * 1.4, 0.06],
    },
  },
  {
    id: '06',
    shortTitle: 'AN',
    stepLabel: '06 // THE COLLECTION',
    title: 'AN ICONIC LEGACY',
    subtitle: 'TIMELESS MONOLITH',
    tagline: 'Architectural Heritage',
    description: 'Encased within the minimalist faceted glass monolith. An enduring symbol of independence, courage, and modern luxury design.',
    bg: '#FAFAFA',
    text: '#1A1A1A',
    secondaryText: '#737373',
    accent: '#8A7B6B',
    noteCategory: 'COLLECTOR EDITION',
    keyNotes: ['Faceted Glass Flacon', 'Hand-Sealed Baudruchage', 'Chanel Seal'],
    pose: {
      rotation: [0, Math.PI * 2, 0],
    },
  },
];
